// Fridge Assistant panel — translations + label maps.
//
// i18n: Dutch for Dutch, French for French, English for anything else.
// Supported languages: nl, fr, en.

export const MONTHS = {
  nl: ["jan", "feb", "mrt", "apr", "mei", "jun", "jul", "aug", "sep", "okt", "nov", "dec"],
  fr: ["janv.", "févr.", "mars", "avr.", "mai", "juin", "juil.", "août", "sept.", "oct.", "nov.", "déc."],
  en: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
};

export const LOCATION_LABELS = {
  nl: { fridge: "Koelkast", freezer: "Vriezer", pantry: "Buiten koelkast" },
  fr: { fridge: "Réfrigérateur", freezer: "Congélateur", pantry: "Garde-manger" },
  en: { fridge: "Fridge", freezer: "Freezer", pantry: "Pantry" },
};

export const CATEGORY_LABELS = {
  nl: {
    vegetables: "Groente", fruit: "Fruit", dairy: "Zuivel", meat: "Vlees", fish: "Vis",
    breakfast: "Ontbijt", lunch: "Lunch", dinner: "Avondeten", snack: "Snack",
    bread_bakery: "Brood & bakkerij", sauces_spices: "Saus & kruiden", drinks: "Dranken",
    eggs: "Eieren", leftovers: "Restjes", other: "Overig",
  },
  fr: {
    vegetables: "Légumes", fruit: "Fruits", dairy: "Produits laitiers", meat: "Viande", fish: "Poisson",
    breakfast: "Petit-déjeuner", lunch: "Déjeuner", dinner: "Dîner", snack: "En-cas",
    bread_bakery: "Pain et boulangerie", sauces_spices: "Sauces et épices", drinks: "Boissons",
    eggs: "Œufs", leftovers: "Restes", other: "Autre",
  },
  en: {
    vegetables: "Vegetables", fruit: "Fruit", dairy: "Dairy", meat: "Meat", fish: "Fish",
    breakfast: "Breakfast", lunch: "Lunch", dinner: "Dinner", snack: "Snack",
    bread_bakery: "Bakery", sauces_spices: "Sauces & spices", drinks: "Drinks",
    eggs: "Eggs", leftovers: "Leftovers", other: "Other",
  },
};

export const KIND_LABELS = {
  nl: {
    ingredient: { label: "Losse ingrediënten", short: "Ingrediënten" },
    dish: { label: "Gerechten", short: "Gerechten" },
  },
  fr: {
    ingredient: { label: "Ingrédients individuels", short: "Ingrédients" },
    dish: { label: "Plats", short: "Plats" },
  },
  en: {
    ingredient: { label: "Individual ingredients", short: "Ingredients" },
    dish: { label: "Dishes", short: "Dishes" },
  },
};

export const STATUS_COLOR = {
  expired: "var(--fa-red)",
  soon: "var(--fa-orange)",
  ok: "var(--fa-green)",
  none: "var(--fa-muted)",
};

export const STRINGS = {
  nl: {
    appTitle: "Koelkast",
    historyTooltip: (n) => (n ? `Geschiedenis (${n})` : "Geschiedenis"),
    manageTemplates: "Templates beheren",
    settings: "Instellingen",
    searchPlaceholder: "Zoek…",
    cleanUp: "Opruimen",
    loading: "Laden…",
    scanAria: "Scan barcode",
    addItemAria: "Item toevoegen",
    itemsUnit: "items",
    soonUnit: "bijna op",
    expiredUnit: "over datum",
    all: "Alles",
    filterScrollPrev: "Filters naar links",
    filterScrollNext: "Filters naar rechts",
    emptyTitle: "Nog niets in de koelkast",
    emptySub: "Voeg je eerste item toe — houdbaarheid wordt automatisch geschat.",
    addItemBtn: '<ha-icon icon="mdi:plus"></ha-icon> Item toevoegen',
    useFirst: '<ha-icon icon="mdi:clock-alert-outline"></ha-icon> Als eerste op',
    nothingFound: "Niets gevonden.",
    printSticker: "Print sticker",
    addNamePlaceholder: "Wat leg je erin? bv. krop sla",
    dateInFieldLabel: "Datum erin",
    expiryLabel: "Houdbaar tot",
    datePickPlaceholder: "Kies datum",
    dateOptionalPlaceholder: "Optioneel",
    clearDateTitle: "Datum wissen",
    moreOptions: "Meer opties ▾",
    lessOptions: "Minder opties ▴",
    displayNameLabel: "Aparte naam (optioneel)",
    displayNamePlaceholder: "Weergavenaam",
    quantityLabel: "Hoeveelheid",
    quantityPlaceholder: "bv. 2 bakjes",
    emojiLabel: "Emoji",
    notesLabel: "Notitie",
    photoUrlLabel: "Foto-URL (optioneel)",
    photoUrlPlaceholder: "https://…",
    chooseTemplateBtn: '<ha-icon icon="mdi:book-multiple"></ha-icon> Template kiezen',
    saveBtn: "Opslaan",
    addBtn: "Toevoegen",
    aiEstimateMini: '<ha-icon icon="mdi:creation"></ha-icon> AI schat',
    unknownProduct: "Onbekend product",
    noTemplateFor: (q, aiEnabled) => `Nog geen template voor "${q}" — vul zelf een datum in${aiEnabled ? " of laat AI schatten" : ""}.`,
    chooseTemplateTitle: "Kies template",
    notSuitableHere: "Niet geschikt voor deze locatie",
    daysAtLocation: (label, days) => `${label}: ${days} dagen`,
    aiEstimateTitle: "AI-schatting",
    otherTemplateTitle: "Andere template",
    useTemplateNameTitle: "Naam van template overnemen",
    notThisManualTitle: "Niet dit — handmatig",
    manualEntry: "Handmatig invullen",
    savedToast: "Opgeslagen ✓",
    addedToast: (code) => `Toegevoegd ✓ ${code ? "code " + code : ""}`,
    printActionLabel: "Print",
    errorPrefix: "Fout: ",
    aiThinking: "✨ AI denkt na…",
    estimatingFor: (name) => `Houdbaarheid van "${name}" schatten…`,
    aiFailed: "AI-schatting mislukt",
    dayUnitShort: "dg",
    aiHint: "Klopt niet helemaal? Tik een dag-getal aan en pas het aan 👇",
    saveAsTemplateLabel: "Bewaar (met jouw aanpassingen) als template",
    pickTemplateTitle: "Kies een template",
    searchInTemplates: (n) => `Zoek in ${n} templates…`,
    ownSuffix: " · eigen",
    templatesTitle: "Templates",
    templateWithAiTitle: "Template met AI",
    newTemplateTitleIcon: "Nieuwe template",
    hiddenTemplatesTitle: "Verborgen standaard-templates",
    searchOrFilterPlaceholder: "Zoek of filter…",
    nothingHidden: "Niets verborgen.",
    backBtn: '<ha-icon icon="mdi:undo-variant"></ha-icon> Terug',
    restoredToast: "Teruggezet ✓",
    nothingInGroup: "Niets in deze groep.",
    customizedBadge: "aangepast",
    ownBadge: "eigen",
    templateWithAiSub: "Typ een product; AI schat de houdbaarheid, jij past aan.",
    productOrDishLabel: "Product of gerecht",
    productOrDishPlaceholder: "bv. zelfgemaakte curry",
    estimateWithAiBtn: '<ha-icon icon="mdi:creation"></ha-icon> Schat met AI',
    aiErrorPrefix: "AI: ",
    newTemplateHeading: "Nieuwe template",
    editTemplateHeading: "Template bewerken",
    overrideNote: "Aanpassing van standaard-template",
    builtinNote: "Standaard-template — wijziging maakt een eigen versie",
    ownTemplateNote: "Eigen template",
    nameLabel: "Naam",
    namePlaceholderTemplate: "bv. Zelfgemaakte pesto",
    kindLabel: "Soort",
    categoryLabel: "Categorie",
    shelfLifeSectionLabel: "Houdbaarheid in dagen — leeg = niet geschikt",
    notApplicablePlaceholder: "n.v.t.",
    aliasesLabel: "Ook herkennen als (komma-gescheiden)",
    aliasesPlaceholder: "pasta bolognese, spaghetti",
    notesTipLabel: "Notitie / bewaartip",
    notesTipPlaceholder: "Laat afkoelen voor invriezen",
    restoreDefaultBtn: '<ha-icon icon="mdi:restore"></ha-icon> Herstel',
    builtinRemoveBtn: '<ha-icon icon="mdi:eye-off-outline"></ha-icon> Verwijder',
    customRemoveBtn: '<ha-icon icon="mdi:delete-outline"></ha-icon> Verwijder',
    templateAddedToast: "Template toegevoegd ✓",
    templateSavedToast: "Template opgeslagen ✓",
    restoredDefaultToast: "Hersteld naar standaard ✓",
    removedFromListToast: "Uit lijst gehaald ✓",
    templateDeletedToast: "Template verwijderd ✓",
    locationLabel: "Locatie",
    addedByLabel: "Toegevoegd door",
    contentsLabel: "Inhoud",
    dateInDetailLabel: "Erin gelegd",
    daysAgoShort: (n) => `${n} dg geleden`,
    stickerBtn: '<ha-icon icon="mdi:tag-outline"></ha-icon> Sticker',
    editBtn: '<ha-icon icon="mdi:pencil-outline"></ha-icon> Bewerken',
    eatenBtn: '<ha-icon icon="mdi:silverware-fork-knife"></ha-icon> Opgegeten',
    tossedBtn: '<ha-icon icon="mdi:delete-outline"></ha-icon> Weggegooid',
    undoLabel: "Ongedaan",
    completedToast: (emoji, name, eaten) => `${emoji} ${name} ${eaten ? "opgegeten" : "weggegooid"}`,
    notOwnLabel: (val) => `Dit is geen eigen koelkast-label (${val})`,
    noActiveItemWithCode: (val) => `Geen actief item met code ${val}`,
    couldNotEatRetry: "Kon niet opeten — probeer opnieuw",
    eatenStatusCount: (name, n) => `🍽️ ${name} opgegeten (${n})`,
    cleanUpTitle: "Koelkast opruimen",
    expiredSection: "Over datum",
    soonSection: "Bijna over datum",
    allGoodMessage: "Alles is nog goed!",
    removeSelectedBtn: "Verwijder geselecteerde",
    removeNItems: (n) => `Verwijder ${n} item${n === 1 ? "" : "s"}`,
    nothingSelected: "Niets geselecteerd",
    cleanedUpToast: (n) => `🧹 ${n} item${n === 1 ? "" : "s"} opgeruimd`,
    scanTitle: "Scan",
    scanSub: "Je koelkast-label om te zoeken, of een winkelbarcode",
    searchModeBtn: '<ha-icon icon="mdi:magnify"></ha-icon> Zoeken',
    eatModeBtn: '<ha-icon icon="mdi:silverware-fork-knife"></ha-icon> Opeten',
    photoBtn: '<ha-icon icon="mdi:camera"></ha-icon> Foto',
    typeCodeBtn: '<ha-icon icon="mdi:keyboard-outline"></ha-icon> Code typen',
    eatModeStatus: "🍽️ Scan je labels — elk item wordt meteen opgegeten",
    aimAtBarcode: "Richt op de barcode…",
    codeInputPlaceholder: "Code, bv. AB12",
    searchBtn: "Zoek",
    readingPhoto: "Foto lezen…",
    noBarcodeFound: "Geen barcode gevonden — probeer dichterbij en scherp.",
    takePhotoOfBarcode: "Maak een foto van de barcode 📸",
    liveScanUnavailable: "Live scannen kan niet op dit toestel. Typ de code.",
    noCameraAccess: "Geen camera-toegang. Gebruik Foto of Code typen.",
    torchTooltip: "Zaklamp",
    foundToast: (name) => `🔎 ${name} gevonden`,
    noActiveItemHistoryHint: (val) => `Geen actief item met code ${val} — misschien al opgegeten/weggegooid (zie Geschiedenis)`,
    unknownCode: (val) => `Onbekende code: ${val}`,
    lookingUpProduct: (code) => `🔎 Product opzoeken… (${code})`,
    retailBarcodeNote: (code) => `Winkelbarcode ${code}`,
    noProductNameFound: (code) => `Geen productnaam gevonden (${code}) — vul zelf in`,
    recognizedBefore: "🔁 Eerder toegevoegd — herkend",
    productFoundToast: (name) => `🛒 ${name}`,
    justNow: "net",
    minutesAgo: (m) => `${m} min geleden`,
    hoursAgo: (h) => `${h} uur geleden`,
    yesterday: "gisteren",
    daysAgo: (d) => `${d} dagen geleden`,
    restoreToFridgeTitle: "Terugzetten in de koelkast",
    historyHeading: "Geschiedenis",
    loadMoreBtn: "Meer laden",
    historyLoadFailed: "Kon geschiedenis niet laden.",
    historyEmpty: "Nog niets opgegeten of weggegooid.",
    historySummary: (total) => `${total} afgerond${total >= 500 ? " (laatste 500)" : ""}`,
    restoreFailedToast: "Herstellen mislukt",
    restoredToFridgeToast: "↩︎ Teruggezet in de koelkast",
    deleteEventTitle: "Definitief verwijderen",
    confirmDeleteLabel: "Zeker?",
    eventDeletedToast: "Definitief verwijderd",
    deleteFailedToast: "Verwijderen mislukt",
    printerLiveNote: (name, size, copies) => `Print via <b>${name}</b> op ${size}-labels${copies > 1 ? ` · ${copies}× per keer` : ""}. Voorbeeld = werkelijke labelmaat.`,
    printerSearching: "Printers zoeken…",
    printerInviteNote: (url) => `Zin om dit als échte sticker te printen? Met de <a href="${url}" target="_blank" rel="noreferrer">Label Printer add-on</a> en een DYMO- of Zebra-labelprinter rolt dit voorbeeld er zo uit. Daarna printen aanzetten bij de instellingen.`,
    printerAddonDownNote: (url) => `De Label Printer add-on is niet bereikbaar op <code>${url}</code>. Draait de add-on?`,
    printerNoPrintersNote: "De add-on draait, maar er is geen labelprinter gevonden op USB. Sluit de printer aan en zet 'm aan, herstart daarna de add-on.",
    printStickerModalTitle: "Sticker printen",
    previewLoading: "Voorbeeld laden…",
    closeBtn: "Sluiten",
    showAll: "Toon alles",
    retryBtn: "Opnieuw proberen",
    subscribeErrorTitle: "Geen verbinding met Fridge Assistant",
    subscribeErrorSub: "De integratie reageert niet. Draait Home Assistant nog op de achtergrond?",
    printBatchStopped: (n, total) => `Printen gestopt na ${n}/${total} stickers.`,
    historyBtnLabel: "Geschiedenis",
    actionFailed: (err) => `Mislukt: ${err}`,
    printBtnLabel: (copies) => `<ha-icon icon="mdi:printer"></ha-icon> Print${copies > 1 ? ` (${copies}×)` : ""}`,
    previewUnavailable: (err) => `Voorbeeld niet beschikbaar: ${err}`,
    workingLabel: "Bezig…",
    stickerPrintedToast: (code, copies) => `🖨️ Sticker ${code} geprint${copies > 1 ? ` (${copies}×)` : ""}`,
    printerDisabledReason: "Printer staat uit — zet 'm aan bij de instellingen.",
    printerUnreachableReason: "Label Printer add-on niet bereikbaar. Staat de add-on aan?",
    printerNotConnectedReason: "De DYMO is niet gevonden. Check kabel/stroom en herstart de add-on.",
    renderFailedReason: "Label renderen mislukte.",
    genericPrintFailed: (reason) => `Printen mislukte (${reason || "?"})`,
    printFailedError: (err) => `Print mislukt: ${err}`,
    portionsLabel: "Porties",
    portionsFieldNote: "Elke portie krijgt een eigen stickercode (bv. AB12-1)",
    portionsStepperNote: "Zo is de batch verdeeld · − haalt een ongebruikte portie weg",
    portionRowLabel: (n) => `Portie ${n}`,
    portionOpenLabel: "open",
    eatPortionTitle: "Deze portie opeten",
    tossPortionTitle: "Deze portie weggooien",
    printPortionTitle: "Sticker voor deze portie printen",
    undoPortionTitle: "Portie terugzetten",
    portionEatenToast: (name, n, total, remaining) => `🍽️ Portie ${n}/${total} van ${name} · nog ${remaining} over`,
    portionTossedToast: (name, n, total, remaining) => `🗑️ Portie ${n}/${total} van ${name} · nog ${remaining} over`,
    portionNotFoundMsg: (val) => `Portie ${val} bestaat niet (meer)`,
    portionConsumedMsg: (val) => `Portie ${val} is al opgegeten of weggegooid`,
    noOpenPortionsMsg: "Geen open porties meer",
    openItemLabel: "Open item",
    printAllStickersBtn: (n) => `<ha-icon icon="mdi:printer"></ha-icon> Print ${n} stickers`,
    printingProgress: (i, n) => `Printen… ${i}/${n}`,
    printedStickersToast: (n, code) => `🖨️ ${n} stickers ${code} geprint`,
    pbadgeTitle: (open, total) => `${open} van ${total} porties over`,
    histPortionLabel: (n, total) => `Portie ${n}${total ? `/${total}` : ""}`,
    portionAddedToast: (n) => `Portie ${n} toegevoegd`,
    secThisWeek: "Deze week",
    secLater: "Later",
    secNoDate: "Zonder datum",
  },
  fr: {
    appTitle: "Réfrigérateur",
    historyTooltip: (n) => (n ? `Historique (${n})` : "Historique"),
    manageTemplates: "Gérer les modèles",
    settings: "Paramètres",
    searchPlaceholder: "Rechercher…",
    cleanUp: "Nettoyer",
    loading: "Chargement…",
    scanAria: "Scanner un code-barres",
    addItemAria: "Ajouter un article",
    itemsUnit: "articles",
    soonUnit: "bientôt périmés",
    expiredUnit: "périmés",
    all: "Tous",
    filterScrollPrev: "Filtres précédents",
    filterScrollNext: "Filtres suivants",
    emptyTitle: "Aucun article dans le réfrigérateur",
    emptySub: "Ajoutez votre premier article — la date limite est estimée automatiquement.",
    addItemBtn: '<ha-icon icon="mdi:plus"></ha-icon> Ajouter un article',
    useFirst: '<ha-icon icon="mdi:clock-alert-outline"></ha-icon> À consommer en premier',
    nothingFound: "Aucun résultat.",
    printSticker: "Imprimer l’étiquette",
    addNamePlaceholder: "Que rangez-vous ? ex. laitue",
    dateInFieldLabel: "Date d’ajout",
    expiryLabel: "À consommer jusqu’au",
    datePickPlaceholder: "Choisir une date",
    dateOptionalPlaceholder: "Facultatif",
    clearDateTitle: "Effacer la date",
    moreOptions: "Plus d’options ▾",
    lessOptions: "Moins d’options ▴",
    displayNameLabel: "Nom personnalisé (facultatif)",
    displayNamePlaceholder: "Nom affiché",
    quantityLabel: "Quantité",
    quantityPlaceholder: "ex. 2 barquettes",
    emojiLabel: "Emoji",
    notesLabel: "Note",
    photoUrlLabel: "URL de la photo (facultatif)",
    photoUrlPlaceholder: "https://…",
    chooseTemplateBtn: '<ha-icon icon="mdi:book-multiple"></ha-icon> Choisir un modèle',
    saveBtn: "Enregistrer",
    addBtn: "Ajouter",
    aiEstimateMini: '<ha-icon icon="mdi:creation"></ha-icon> Estimation IA',
    unknownProduct: "Produit inconnu",
    noTemplateFor: (q, aiEnabled) => `Aucun modèle pour « ${q} » — saisissez vous-même une date${aiEnabled ? " ou laissez l’IA l’estimer" : ""}.`,
    chooseTemplateTitle: "Choisir un modèle",
    notSuitableHere: "Ne convient pas à cet emplacement",
    daysAtLocation: (label, days) => `${label} : ${days} jours`,
    aiEstimateTitle: "Estimation par IA",
    otherTemplateTitle: "Autre modèle",
    useTemplateNameTitle: "Utiliser le nom du modèle",
    notThisManualTitle: "Ce n’est pas le bon — saisie manuelle",
    manualEntry: "Saisie manuelle",
    savedToast: "Enregistré ✓",
    addedToast: (code) => `Ajouté ✓ ${code ? "code " + code : ""}`,
    printActionLabel: "Imprimer",
    errorPrefix: "Erreur : ",
    aiThinking: "✨ L’IA réfléchit…",
    estimatingFor: (name) => `Estimation de la durée de conservation de « ${name} »…`,
    aiFailed: "Échec de l’estimation par IA",
    dayUnitShort: "j",
    aiHint: "Ce n’est pas tout à fait correct ? Touchez un nombre de jours pour le modifier 👇",
    saveAsTemplateLabel: "Enregistrer avec vos modifications comme modèle",
    pickTemplateTitle: "Choisir un modèle",
    searchInTemplates: (n) => `Rechercher parmi ${n} modèles…`,
    ownSuffix: " · personnalisé",
    templatesTitle: "Modèles",
    templateWithAiTitle: "Modèle avec IA",
    newTemplateTitleIcon: "Nouveau modèle",
    hiddenTemplatesTitle: "Modèles intégrés masqués",
    searchOrFilterPlaceholder: "Rechercher ou filtrer…",
    nothingHidden: "Aucun élément masqué.",
    backBtn: '<ha-icon icon="mdi:undo-variant"></ha-icon> Retour',
    restoredToast: "Restauré ✓",
    nothingInGroup: "Aucun élément dans ce groupe.",
    customizedBadge: "personnalisé",
    ownBadge: "personnel",
    templateWithAiSub: "Saisissez un produit ; l’IA estime sa durée de conservation, puis vous pouvez l’ajuster.",
    productOrDishLabel: "Produit ou plat",
    productOrDishPlaceholder: "ex. curry maison",
    estimateWithAiBtn: '<ha-icon icon="mdi:creation"></ha-icon> Estimer avec l’IA',
    aiErrorPrefix: "IA : ",
    newTemplateHeading: "Nouveau modèle",
    editTemplateHeading: "Modifier le modèle",
    overrideNote: "Personnalisation d’un modèle intégré",
    builtinNote: "Modèle intégré — sa modification crée votre propre version",
    ownTemplateNote: "Votre propre modèle",
    nameLabel: "Nom",
    namePlaceholderTemplate: "ex. Pesto maison",
    kindLabel: "Type",
    categoryLabel: "Catégorie",
    shelfLifeSectionLabel: "Durée de conservation en jours — vide = ne convient pas",
    notApplicablePlaceholder: "n/a",
    aliasesLabel: "Également reconnu comme (séparés par des virgules)",
    aliasesPlaceholder: "pâtes bolognaises, spaghetti",
    notesTipLabel: "Note / conseil de conservation",
    notesTipPlaceholder: "Laisser refroidir avant de congeler",
    restoreDefaultBtn: '<ha-icon icon="mdi:restore"></ha-icon> Restaurer',
    builtinRemoveBtn: '<ha-icon icon="mdi:eye-off-outline"></ha-icon> Supprimer',
    customRemoveBtn: '<ha-icon icon="mdi:delete-outline"></ha-icon> Supprimer',
    templateAddedToast: "Modèle ajouté ✓",
    templateSavedToast: "Modèle enregistré ✓",
    restoredDefaultToast: "Rétabli par défaut ✓",
    removedFromListToast: "Retiré de la liste ✓",
    templateDeletedToast: "Modèle supprimé ✓",
    locationLabel: "Emplacement",
    addedByLabel: "Ajouté par",
    contentsLabel: "Contenu",
    dateInDetailLabel: "Ajouté le",
    daysAgoShort: (n) => `il y a ${n} j`,
    stickerBtn: '<ha-icon icon="mdi:tag-outline"></ha-icon> Étiquette',
    editBtn: '<ha-icon icon="mdi:pencil-outline"></ha-icon> Modifier',
    eatenBtn: '<ha-icon icon="mdi:silverware-fork-knife"></ha-icon> Consommé',
    tossedBtn: '<ha-icon icon="mdi:delete-outline"></ha-icon> Jeté',
    undoLabel: "Annuler",
    completedToast: (emoji, name, eaten) => `${emoji} ${name} ${eaten ? "consommé" : "jeté"}`,
    notOwnLabel: (val) => `Cette étiquette ne provient pas de votre réfrigérateur (${val})`,
    noActiveItemWithCode: (val) => `Aucun article actif avec le code ${val}`,
    couldNotEatRetry: "Impossible de marquer comme consommé — réessayez",
    eatenStatusCount: (name, n) => `🍽️ ${name} consommé (${n})`,
    cleanUpTitle: "Nettoyer le réfrigérateur",
    expiredSection: "Date dépassée",
    soonSection: "Expire bientôt",
    allGoodMessage: "Tout est encore bon !",
    removeSelectedBtn: "Supprimer la sélection",
    removeNItems: (n) => `Supprimer ${n} article${n === 1 ? "" : "s"}`,
    nothingSelected: "Aucun élément sélectionné",
    cleanedUpToast: (n) => `🧹 ${n} article${n === 1 ? "" : "s"} nettoyé${n === 1 ? "" : "s"}`,
    scanTitle: "Scanner",
    scanSub: "Une étiquette du réfrigérateur pour rechercher un article, ou un code-barres de magasin",
    searchModeBtn: '<ha-icon icon="mdi:magnify"></ha-icon> Rechercher',
    eatModeBtn: '<ha-icon icon="mdi:silverware-fork-knife"></ha-icon> Consommer',
    photoBtn: '<ha-icon icon="mdi:camera"></ha-icon> Photo',
    typeCodeBtn: '<ha-icon icon="mdi:keyboard-outline"></ha-icon> Saisir le code',
    eatModeStatus: "🍽️ Scannez vos étiquettes — chaque article est immédiatement marqué comme consommé",
    aimAtBarcode: "Visez le code-barres…",
    codeInputPlaceholder: "Code, ex. AB12",
    searchBtn: "Rechercher",
    readingPhoto: "Lecture de la photo…",
    noBarcodeFound: "Aucun code-barres trouvé — rapprochez-vous et faites la mise au point.",
    takePhotoOfBarcode: "Prenez une photo du code-barres 📸",
    liveScanUnavailable: "Le scan en direct n’est pas disponible sur cet appareil. Saisissez le code.",
    noCameraAccess: "Accès à la caméra impossible. Utilisez Photo ou Saisir le code.",
    torchTooltip: "Lampe torche",
    foundToast: (name) => `🔎 ${name} trouvé`,
    noActiveItemHistoryHint: (val) => `Aucun article actif avec le code ${val} — il a peut-être déjà été consommé ou jeté (voir l’historique)`,
    unknownCode: (val) => `Code inconnu : ${val}`,
    lookingUpProduct: (code) => `🔎 Recherche du produit… (${code})`,
    retailBarcodeNote: (code) => `Code-barres du produit ${code}`,
    noProductNameFound: (code) => `Aucun nom de produit trouvé (${code}) — saisissez-le vous-même`,
    recognizedBefore: "🔁 Déjà ajouté — reconnu",
    productFoundToast: (name) => `🛒 ${name}`,
    justNow: "à l’instant",
    minutesAgo: (m) => `il y a ${m} min`,
    hoursAgo: (h) => `il y a ${h} heure${h === 1 ? "" : "s"}`,
    yesterday: "hier",
    daysAgo: (d) => `il y a ${d} jour${d === 1 ? "" : "s"}`,
    restoreToFridgeTitle: "Remettre dans le réfrigérateur",
    historyHeading: "Historique",
    loadMoreBtn: "Charger plus",
    historyLoadFailed: "Impossible de charger l’historique.",
    historyEmpty: "Aucun article consommé ou jeté pour le moment.",
    historySummary: (total) => `${total} élément${total === 1 ? "" : "s"} terminé${total === 1 ? "" : "s"}${total >= 500 ? " (500 derniers)" : ""}`,
    restoreFailedToast: "Échec de la restauration",
    restoredToFridgeToast: "↩︎ Remis dans le réfrigérateur",
    deleteEventTitle: "Supprimer définitivement",
    confirmDeleteLabel: "Êtes-vous sûr ?",
    eventDeletedToast: "Supprimé définitivement",
    deleteFailedToast: "Échec de la suppression",
    printerLiveNote: (name, size, copies) => `Impression via <b>${name}</b> sur des étiquettes de ${size}${copies > 1 ? ` · ${copies}× par pression` : ""}. L’aperçu correspond à la taille réelle de l’étiquette.`,
    printerSearching: "Recherche d’imprimantes…",
    printerInviteNote: (url) => `Envie d’imprimer ceci sur une véritable étiquette ? Avec l’<a href="${url}" target="_blank" rel="noreferrer">extension Label Printer</a> et une imprimante DYMO ou Zebra, cet aperçu peut être imprimé directement. Activez ensuite l’impression dans les paramètres.`,
    printerAddonDownNote: (url) => `L’extension Label Printer est inaccessible à l’adresse <code>${url}</code>. Est-elle en cours d’exécution ?`,
    printerNoPrintersNote: "L’extension est active, mais aucune imprimante d’étiquettes n’a été trouvée en USB. Branchez et allumez l’imprimante, puis redémarrez l’extension.",
    printStickerModalTitle: "Imprimer l’étiquette",
    previewLoading: "Chargement de l’aperçu…",
    closeBtn: "Fermer",
    showAll: "Tout afficher",
    retryBtn: "Réessayer",
    subscribeErrorTitle: "Aucune connexion à Fridge Assistant",
    subscribeErrorSub: "L’intégration ne répond pas. Home Assistant fonctionne-t-il toujours en arrière-plan ?",
    printBatchStopped: (n, total) => `Impression arrêtée après ${n}/${total} étiquettes.`,
    historyBtnLabel: "Historique",
    actionFailed: (err) => `Échec : ${err}`,
    printBtnLabel: (copies) => `<ha-icon icon="mdi:printer"></ha-icon> Imprimer${copies > 1 ? ` (${copies}×)` : ""}`,
    previewUnavailable: (err) => `Aperçu indisponible : ${err}`,
    workingLabel: "Traitement…",
    stickerPrintedToast: (code, copies) => `🖨️ Étiquette ${code} imprimée${copies > 1 ? ` (${copies}×)` : ""}`,
    printerDisabledReason: "L’imprimante est désactivée — activez-la dans les paramètres.",
    printerUnreachableReason: "L’extension Label Printer est inaccessible. Est-elle en cours d’exécution ?",
    printerNotConnectedReason: "La DYMO n’a pas été trouvée. Vérifiez le câble et l’alimentation, puis redémarrez l’extension.",
    renderFailedReason: "Échec du rendu de l’étiquette.",
    genericPrintFailed: (reason) => `Échec de l’impression (${reason || "?"})`,
    printFailedError: (err) => `Échec de l’impression : ${err}`,
    portionsLabel: "Portions",
    portionsFieldNote: "Chaque portion reçoit son propre code d’étiquette (ex. AB12-1)",
    portionsStepperNote: "Répartition du lot · − supprime une portion inutilisée",
    portionRowLabel: (n) => `Portion ${n}`,
    portionOpenLabel: "ouverte",
    eatPortionTitle: "Consommer cette portion",
    tossPortionTitle: "Jeter cette portion",
    printPortionTitle: "Imprimer l’étiquette de cette portion",
    undoPortionTitle: "Remettre la portion",
    portionEatenToast: (name, n, total, remaining) => `🍽️ Portion ${n}/${total} de ${name} · ${remaining} restante${remaining === 1 ? "" : "s"}`,
    portionTossedToast: (name, n, total, remaining) => `🗑️ Portion ${n}/${total} de ${name} · ${remaining} restante${remaining === 1 ? "" : "s"}`,
    portionNotFoundMsg: (val) => `La portion ${val} n’existe plus`,
    portionConsumedMsg: (val) => `La portion ${val} a déjà été consommée ou jetée`,
    noOpenPortionsMsg: "Il ne reste aucune portion ouverte",
    openItemLabel: "Article ouvert",
    printAllStickersBtn: (n) => `<ha-icon icon="mdi:printer"></ha-icon> Imprimer ${n} étiquette${n === 1 ? "" : "s"}`,
    printingProgress: (i, n) => `Impression… ${i}/${n}`,
    printedStickersToast: (n, code) => `🖨️ ${n} étiquette${n === 1 ? "" : "s"} ${code} imprimée${n === 1 ? "" : "s"}`,
    pbadgeTitle: (open, total) => `${open} portion${open === 1 ? "" : "s"} sur ${total} restante${open === 1 ? "" : "s"}`,
    histPortionLabel: (n, total) => `Portion ${n}${total ? `/${total}` : ""}`,
    portionAddedToast: (n) => `Portion ${n} ajoutée`,
    secThisWeek: "Cette semaine",
    secLater: "Plus tard",
    secNoDate: "Sans date",
  },
  en: {
    appTitle: "Fridge",
    historyTooltip: (n) => (n ? `History (${n})` : "History"),
    manageTemplates: "Manage templates",
    settings: "Settings",
    searchPlaceholder: "Search…",
    cleanUp: "Clean up",
    loading: "Loading…",
    scanAria: "Scan barcode",
    addItemAria: "Add item",

    itemsUnit: "items",
    soonUnit: "soon",
    expiredUnit: "expired",
    all: "All",
    filterScrollPrev: "Previous filters",
    filterScrollNext: "Next filters",

    emptyTitle: "Nothing in the fridge yet",
    emptySub: "Add your first item — expiry is estimated automatically.",
    addItemBtn: '<ha-icon icon="mdi:plus"></ha-icon> Add item',
    useFirst: '<ha-icon icon="mdi:clock-alert-outline"></ha-icon> Use first',
    nothingFound: "Nothing found.",
    printSticker: "Print sticker",

    addNamePlaceholder: "What are you putting in? e.g. lettuce",
    dateInFieldLabel: "Date added",
    expiryLabel: "Use by",
    datePickPlaceholder: "Pick a date",
    dateOptionalPlaceholder: "Optional",
    clearDateTitle: "Clear date",
    moreOptions: "More options ▾",
    lessOptions: "Fewer options ▴",
    displayNameLabel: "Custom name (optional)",
    displayNamePlaceholder: "Display name",
    quantityLabel: "Quantity",
    quantityPlaceholder: "e.g. 2 containers",
    emojiLabel: "Emoji",
    notesLabel: "Note",
    photoUrlLabel: "Photo URL (optional)",
    photoUrlPlaceholder: "https://…",
    chooseTemplateBtn: '<ha-icon icon="mdi:book-multiple"></ha-icon> Choose template',
    saveBtn: "Save",
    addBtn: "Add",
    aiEstimateMini: '<ha-icon icon="mdi:creation"></ha-icon> AI estimate',
    unknownProduct: "Unknown product",
    noTemplateFor: (q, aiEnabled) =>
      `No template yet for "${q}" — enter a date yourself${aiEnabled ? " or let AI estimate" : ""}.`,
    chooseTemplateTitle: "Choose template",
    notSuitableHere: "Not suitable for this location",
    daysAtLocation: (label, days) => `${label}: ${days} days`,
    aiEstimateTitle: "AI estimate",
    otherTemplateTitle: "Different template",
    useTemplateNameTitle: "Use the template's name",
    notThisManualTitle: "Not this — manual",
    manualEntry: "Manual entry",
    savedToast: "Saved ✓",
    addedToast: (code) => `Added ✓ ${code ? "code " + code : ""}`,
    printActionLabel: "Print",
    errorPrefix: "Error: ",

    aiThinking: "✨ AI is thinking…",
    estimatingFor: (name) => `Estimating shelf life for "${name}"…`,
    aiFailed: "AI estimate failed",
    dayUnitShort: "d",
    aiHint: "Not quite right? Tap a day count to adjust it 👇",
    saveAsTemplateLabel: "Save (with your edits) as a template",

    pickTemplateTitle: "Choose a template",
    searchInTemplates: (n) => `Search ${n} templates…`,
    ownSuffix: " · custom",

    templatesTitle: "Templates",
    templateWithAiTitle: "Template with AI",
    newTemplateTitleIcon: "New template",
    hiddenTemplatesTitle: "Hidden built-in templates",
    searchOrFilterPlaceholder: "Search or filter…",
    nothingHidden: "Nothing hidden.",
    backBtn: '<ha-icon icon="mdi:undo-variant"></ha-icon> Back',
    restoredToast: "Restored ✓",
    nothingInGroup: "Nothing in this group.",
    customizedBadge: "customized",
    ownBadge: "custom",

    templateWithAiSub: "Type a product; AI estimates shelf life, you adjust it.",
    productOrDishLabel: "Product or dish",
    productOrDishPlaceholder: "e.g. homemade curry",
    estimateWithAiBtn: '<ha-icon icon="mdi:creation"></ha-icon> Estimate with AI',
    aiErrorPrefix: "AI: ",

    newTemplateHeading: "New template",
    editTemplateHeading: "Edit template",
    overrideNote: "Customization of a built-in template",
    builtinNote: "Built-in template — editing creates your own version",
    ownTemplateNote: "Your own template",
    nameLabel: "Name",
    namePlaceholderTemplate: "e.g. Homemade pesto",
    kindLabel: "Kind",
    categoryLabel: "Category",
    shelfLifeSectionLabel: "Shelf life in days — empty = not suitable",
    notApplicablePlaceholder: "n/a",
    aliasesLabel: "Also recognize as (comma-separated)",
    aliasesPlaceholder: "pasta bolognese, spaghetti",
    notesTipLabel: "Note / storage tip",
    notesTipPlaceholder: "Let cool before freezing",
    restoreDefaultBtn: '<ha-icon icon="mdi:restore"></ha-icon> Restore',
    builtinRemoveBtn: '<ha-icon icon="mdi:eye-off-outline"></ha-icon> Remove',
    customRemoveBtn: '<ha-icon icon="mdi:delete-outline"></ha-icon> Remove',
    templateAddedToast: "Template added ✓",
    templateSavedToast: "Template saved ✓",
    restoredDefaultToast: "Restored to default ✓",
    removedFromListToast: "Removed from list ✓",
    templateDeletedToast: "Template deleted ✓",

    locationLabel: "Location",
    addedByLabel: "Added by",
    contentsLabel: "Contents",
    dateInDetailLabel: "Added on",
    daysAgoShort: (n) => `${n}d ago`,
    stickerBtn: '<ha-icon icon="mdi:tag-outline"></ha-icon> Sticker',
    editBtn: '<ha-icon icon="mdi:pencil-outline"></ha-icon> Edit',
    eatenBtn: '<ha-icon icon="mdi:silverware-fork-knife"></ha-icon> Eaten',
    tossedBtn: '<ha-icon icon="mdi:delete-outline"></ha-icon> Tossed',

    undoLabel: "Undo",
    completedToast: (emoji, name, eaten) => `${emoji} ${name} ${eaten ? "eaten" : "tossed"}`,

    notOwnLabel: (val) => `This isn't one of your own fridge labels (${val})`,
    noActiveItemWithCode: (val) => `No active item with code ${val}`,
    couldNotEatRetry: "Couldn't mark as eaten — try again",
    eatenStatusCount: (name, n) => `🍽️ ${name} eaten (${n})`,

    cleanUpTitle: "Clean up the fridge",
    expiredSection: "Past date",
    soonSection: "Expiring soon",
    allGoodMessage: "Everything is still good!",
    removeSelectedBtn: "Remove selected",
    removeNItems: (n) => `Remove ${n} item${n === 1 ? "" : "s"}`,
    nothingSelected: "Nothing selected",
    cleanedUpToast: (n) => `🧹 ${n} item${n === 1 ? "" : "s"} cleaned up`,

    scanTitle: "Scan",
    scanSub: "Your fridge label to search, or a retail barcode",
    searchModeBtn: '<ha-icon icon="mdi:magnify"></ha-icon> Search',
    eatModeBtn: '<ha-icon icon="mdi:silverware-fork-knife"></ha-icon> Eat',
    photoBtn: '<ha-icon icon="mdi:camera"></ha-icon> Photo',
    typeCodeBtn: '<ha-icon icon="mdi:keyboard-outline"></ha-icon> Type code',
    eatModeStatus: "🍽️ Scan your labels — each item is marked eaten right away",
    aimAtBarcode: "Point at the barcode…",
    codeInputPlaceholder: "Code, e.g. AB12",
    searchBtn: "Search",
    readingPhoto: "Reading photo…",
    noBarcodeFound: "No barcode found — try closer and in focus.",
    takePhotoOfBarcode: "Take a photo of the barcode 📸",
    liveScanUnavailable: "Live scanning isn't available on this device. Type the code.",
    noCameraAccess: "No camera access. Use Photo or Type code.",
    torchTooltip: "Flashlight",

    foundToast: (name) => `🔎 ${name} found`,
    noActiveItemHistoryHint: (val) => `No active item with code ${val} — maybe already eaten/tossed (see History)`,
    unknownCode: (val) => `Unknown code: ${val}`,

    lookingUpProduct: (code) => `🔎 Looking up product… (${code})`,
    retailBarcodeNote: (code) => `Retail barcode ${code}`,
    noProductNameFound: (code) => `No product name found (${code}) — fill it in yourself`,
    recognizedBefore: "🔁 Added before — recognized",
    productFoundToast: (name) => `🛒 ${name}`,

    justNow: "just now",
    minutesAgo: (m) => `${m} min ago`,
    hoursAgo: (h) => `${h} hour${h === 1 ? "" : "s"} ago`,
    yesterday: "yesterday",
    daysAgo: (d) => `${d} days ago`,

    restoreToFridgeTitle: "Put back in the fridge",
    historyHeading: "History",
    loadMoreBtn: "Load more",
    historyLoadFailed: "Couldn't load history.",
    historyEmpty: "Nothing eaten or tossed yet.",
    historySummary: (total) => `${total} completed${total >= 500 ? " (last 500)" : ""}`,
    restoreFailedToast: "Restore failed",
    restoredToFridgeToast: "↩︎ Put back in the fridge",
    deleteEventTitle: "Delete permanently",
    confirmDeleteLabel: "Sure?",
    eventDeletedToast: "Deleted permanently",
    deleteFailedToast: "Delete failed",

    printerLiveNote: (name, size, copies) =>
      `Prints via <b>${name}</b> on ${size} labels${copies > 1 ? ` · ${copies}× per tap` : ""}. Preview = actual label size.`,
    printerSearching: "Looking for printers…",
    printerInviteNote: (url) =>
      `Want this as a real sticker? With the <a href="${url}" target="_blank" rel="noreferrer">Label Printer add-on</a> and a DYMO or Zebra label printer this preview rolls right out. Then enable printing in the settings.`,
    printerAddonDownNote: (url) =>
      `The Label Printer add-on is unreachable at <code>${url}</code>. Is it running?`,
    printerNoPrintersNote:
      "The add-on is running, but no label printer was found on USB. Connect and power on the printer, then restart the add-on.",
    printStickerModalTitle: "Print sticker",
    previewLoading: "Loading preview…",
    closeBtn: "Close",
    showAll: "Show all",
    retryBtn: "Try again",
    subscribeErrorTitle: "No connection to Fridge Assistant",
    subscribeErrorSub: "The integration is not responding. Is Home Assistant still running in the background?",
    printBatchStopped: (n, total) => `Printing stopped after ${n}/${total} stickers.`,
    historyBtnLabel: "History",
    actionFailed: (err) => `Failed: ${err}`,
    printBtnLabel: (copies) => `<ha-icon icon="mdi:printer"></ha-icon> Print${copies > 1 ? ` (${copies}×)` : ""}`,
    previewUnavailable: (err) => `Preview unavailable: ${err}`,
    workingLabel: "Working…",
    stickerPrintedToast: (code, copies) => `🖨️ Sticker ${code} printed${copies > 1 ? ` (${copies}×)` : ""}`,
    printerDisabledReason: "Printer is off — enable it in the settings.",
    printerUnreachableReason: "Label Printer add-on unreachable. Is the add-on running?",
    printerNotConnectedReason: "The DYMO wasn't found. Check cable/power and restart the add-on.",
    renderFailedReason: "Rendering the label failed.",
    genericPrintFailed: (reason) => `Printing failed (${reason || "?"})`,
    printFailedError: (err) => `Print failed: ${err}`,

    portionsLabel: "Portions",
    portionsFieldNote: "Each portion gets its own sticker code (e.g. AB12-1)",
    portionsStepperNote: "How the batch is split · − removes an unused portion",
    portionRowLabel: (n) => `Portion ${n}`,
    portionOpenLabel: "open",
    eatPortionTitle: "Eat this portion",
    tossPortionTitle: "Toss this portion",
    printPortionTitle: "Print this portion's sticker",
    undoPortionTitle: "Put portion back",
    portionEatenToast: (name, n, total, remaining) =>
      `🍽️ Portion ${n}/${total} of ${name} · ${remaining} left`,
    portionTossedToast: (name, n, total, remaining) =>
      `🗑️ Portion ${n}/${total} of ${name} · ${remaining} left`,
    portionNotFoundMsg: (val) => `Portion ${val} does not exist (anymore)`,
    portionConsumedMsg: (val) => `Portion ${val} was already eaten or tossed`,
    noOpenPortionsMsg: "No open portions left",
    openItemLabel: "Open item",
    printAllStickersBtn: (n) => `<ha-icon icon="mdi:printer"></ha-icon> Print ${n} stickers`,
    printingProgress: (i, n) => `Printing… ${i}/${n}`,
    printedStickersToast: (n, code) => `🖨️ ${n} stickers ${code} printed`,
    pbadgeTitle: (open, total) => `${open} of ${total} portions left`,
    histPortionLabel: (n, total) => `Portion ${n}${total ? `/${total}` : ""}`,
    portionAddedToast: (n) => `Portion ${n} added`,

    secThisWeek: "This week",
    secLater: "Later",
    secNoDate: "No date",
  },
};
