// Builtin seed template display names (nl names live in seed_templates.json).
// i18n: fr and en only; nl falls back to the seed name.

export const TEMPLATE_NAMES = {
  "krop-sla": { fr: "Laitue en pomme", en: "Head lettuce" },
  "spinazie": { fr: "Épinards", en: "Spinach" },
  "wortel": { fr: "Carotte", en: "Carrot" },
  "broccoli": { fr: "Brocoli", en: "Broccoli" },
  "komkommer": { fr: "Concombre", en: "Cucumber" },
  "paprika": { fr: "Poivron", en: "Bell pepper" },
  "ui": { fr: "Oignon", en: "Onion" },
  "aardappel": { fr: "Pomme de terre", en: "Potato" },
  "tomaat": { fr: "Tomate", en: "Tomato" },
  "bloemkool": { fr: "Chou-fleur", en: "Cauliflower" },
  "courgette": { fr: "Courgette", en: "Zucchini" },
  "champignons": { fr: "Champignons", en: "Mushrooms" },
  "sperziebonen": { fr: "Haricots verts", en: "Green beans" },
  "prei": { fr: "Poireau", en: "Leek" },
  "andijvie": { fr: "Scarole", en: "Endive" },
  "boerenkool": { fr: "Chou frisé", en: "Kale" },
  "banaan": { fr: "Banane", en: "Banana" },
  "appel": { fr: "Pomme", en: "Apple" },
  "aardbeien": { fr: "Fraises", en: "Strawberries" },
  "druiven": { fr: "Raisins", en: "Grapes" },
  "citroen": { fr: "Citron", en: "Lemon" },
  "sinaasappel": { fr: "Orange", en: "Orange" },
  "peer": { fr: "Poire", en: "Pear" },
  "blauwe-bessen": { fr: "Myrtilles", en: "Blueberries" },
  "mango": { fr: "Mangue", en: "Mango" },
  "avocado": { fr: "Avocat", en: "Avocado" },
  "kiwi": { fr: "Kiwi", en: "Kiwi" },
  "melk": { fr: "Lait", en: "Milk" },
  "yoghurt": { fr: "Yaourt", en: "Yogurt" },
  "jonge-kaas": { fr: "Fromage jeune", en: "Young cheese" },
  "oude-kaas": { fr: "Fromage affiné", en: "Aged cheese" },
  "roomkaas": { fr: "Fromage à tartiner", en: "Cream cheese" },
  "boter": { fr: "Beurre", en: "Butter" },
  "slagroom": { fr: "Crème fouettée", en: "Whipping cream" },
  "kwark": { fr: "Fromage blanc", en: "Quark" },
  "karnemelk": { fr: "Babeurre", en: "Buttermilk" },
  "creme-fraiche": { fr: "Crème fraîche", en: "Crème fraîche" },
  "geraspte-kaas": { fr: "Fromage râpé", en: "Grated cheese" },
  "kipfilet-rauw": { fr: "Blanc de poulet cru", en: "Raw chicken breast" },
  "gehakt-rauw": { fr: "Viande hachée crue", en: "Raw ground meat" },
  "spek": { fr: "Bacon", en: "Bacon" },
  "kip-gebraden": { fr: "Poulet rôti", en: "Roast chicken" },
  "rookworst": { fr: "Saucisse fumée", en: "Smoked sausage" },
  "ham-vleeswaren": { fr: "Jambon", en: "Ham" },
  "salami": { fr: "Salami", en: "Salami" },
  "biefstuk-rauw": { fr: "Steak cru", en: "Raw steak" },
  "hamburger-rauw": { fr: "Steak haché cru", en: "Raw burger patty" },
  "zalm-rauw": { fr: "Saumon cru", en: "Raw salmon" },
  "garnalen": { fr: "Crevettes", en: "Shrimp" },
  "witvis-kabeljauw": { fr: "Poisson blanc", en: "White fish" },
  "gerookte-zalm": { fr: "Saumon fumé", en: "Smoked salmon" },
  "tonijn-blik-open": { fr: "Thon en conserve (ouvert)", en: "Canned tuna (open)" },
  "haring": { fr: "Hareng", en: "Herring" },
  "macaroni-met-vlees": { fr: "Macaroni à la viande", en: "Macaroni with meat" },
  "nasi": { fr: "Nasi", en: "Nasi goreng" },
  "verse-soep": { fr: "Soupe fraîche", en: "Fresh soup" },
  "stamppot": { fr: "Purée-hachis", en: "Stamppot" },
  "rijst-gekookt": { fr: "Riz cuit", en: "Cooked rice" },
  "pasta-gekookt": { fr: "Pâtes cuites", en: "Cooked pasta" },
  "curry": { fr: "Curry", en: "Curry" },
  "lasagne": { fr: "Lasagnes", en: "Lasagna" },
  "pannenkoeken": { fr: "Crêpes", en: "Pancakes" },
  "bami": { fr: "Bami", en: "Bami goreng" },
  "aardappelpuree": { fr: "Purée de pommes de terre", en: "Mashed potatoes" },
  "groentesoep": { fr: "Soupe aux légumes", en: "Vegetable soup" },
  "brood": { fr: "Pain", en: "Bread" },
  "croissant": { fr: "Croissant", en: "Croissant" },
  "wraps": { fr: "Wraps", en: "Wraps" },
  "bagels": { fr: "Bagels", en: "Bagels" },
  "beschuit": { fr: "Biscottes", en: "Rusks" },
  "krentenbollen": { fr: "Petits pains aux raisins", en: "Currant buns" },
  "pesto": { fr: "Pesto (ouvert)", en: "Pesto (open)" },
  "mayonaise-open": { fr: "Mayonnaise (ouverte)", en: "Mayonnaise (open)" },
  "ketchup-open": { fr: "Ketchup (ouverte)", en: "Ketchup (open)" },
  "hummus": { fr: "Houmous", en: "Hummus" },
  "tomatensaus-open": { fr: "Sauce tomate (ouverte)", en: "Tomato sauce (open)" },
  "mosterd-open": { fr: "Moutarde (ouverte)", en: "Mustard (open)" },
  "sojasaus-open": { fr: "Sauce soja (ouverte)", en: "Soy sauce (open)" },
  "appelmoes-open": { fr: "Compote de pommes (ouverte)", en: "Apple sauce (open)" },
  "verse-pesto-koelvers": { fr: "Pesto frais (réfrigéré)", en: "Fresh pesto (chilled)" },
  "verse-jus": { fr: "Jus d'orange frais", en: "Fresh orange juice" },
  "open-witte-wijn": { fr: "Vin blanc ouvert", en: "Open white wine" },
  "open-rode-wijn": { fr: "Vin rouge ouvert", en: "Open red wine" },
  "plantaardige-melk-open": { fr: "Lait végétal (ouvert)", en: "Plant milk (open)" },
  "vruchtensap-open": { fr: "Jus de fruits (ouvert)", en: "Fruit juice (open)" },
  "eieren": { fr: "Œufs", en: "Eggs" },
  "gekookt-ei": { fr: "Œuf dur", en: "Boiled egg" },
  "restjes-algemeen": { fr: "Restes", en: "Leftovers" },
  "restjes-ovenschotel": { fr: "Restes de gratin", en: "Leftover casserole" },
  "tofu-open": { fr: "Tofu (ouverte)", en: "Tofu (open)" },
  "olijven-open": { fr: "Olives (ouvertes)", en: "Olives (open)" },
  "verse-basilicum": { fr: "Basilic frais", en: "Fresh basil" },
  "tuinbonen": { fr: "Fèves", en: "Broad beans" },
  "doperwten": { fr: "Petits pois", en: "Peas" },
  "mais": { fr: "Maïs", en: "Corn" },
  "frambozen": { fr: "Framboises", en: "Raspberries" },
  "meloen": { fr: "Melon", en: "Melon" },
  "pizza-margherita": { fr: "Pizza margherita", en: "Margherita pizza" },
  "pindakaas": { fr: "Beurre de cacahuète", en: "Peanut butter" },
};

/** Localized display name for a template row (custom/user overrides keep stored name). */
export function templateDisplayName(tpl, lang) {
  if (!tpl) return "";
  if (tpl.custom) return tpl.name || "";
  const row = TEMPLATE_NAMES[tpl.id];
  if (row && row[lang]) return row[lang];
  return tpl.name || "";
}
